/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2020-12-26 17:06:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.front_002dend.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.member.model.*;

public final class Member_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1608636200000L));
    _jspx_dependants.put("jar:file:/Users/tomgu/CEA101_WebApp/CEA101G3/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/CEA101G3/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1064305020000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.member.model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	MemberVO memVO = (MemberVO) session.getAttribute("memVO");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900\" rel=\"stylesheet\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://pro.fontawesome.com/releases/v5.10.0/css/all.css\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/front-end/member.css\">\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/png\" href=\"");
      out.print(request.getContextPath());
      out.write("/img/logo.png\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" integrity=\"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u\" crossorigin=\"anonymous\">\n");
      out.write("<title>Maison Camp | 會員中心</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <header class=\"header\">\n");
      out.write("        <nav role=\"navigation\">\n");
      out.write("            <div id=\"menuToggle\">\n");
      out.write("                <input type=\"checkbox\" id=\"checkboxtoggle\"/>\n");
      out.write("                <span></span>\n");
      out.write("                <span></span>\n");
      out.write("                <span></span>\n");
      out.write("                <ul id=\"menu\">\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/front-end/front-index.jsp\"><li>首頁</li></a>\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/front-end/news/News.jsp\"><li>最新消息</li></a>\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/front-end/member/Member.jsp\"><li>會員中心</li></a>\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/front-end/room-type/RoomType.jsp\"><li>帳型介紹</li></a>\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/front-end/room-booking/RoomBooking.jsp\"><li>立即訂房</li></a>\n");
      out.write("                    <a href=\"#\"><li>精選商城</li></a>\n");
      out.write("                    <a href=\"#\"><li>活動預約</li></a>\n");
      out.write("                    <a href=\"#\"><li>聯絡我們</li></a>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </nav>          \n");
      out.write("        <a href=\"#\"><img id=\"logoo\" class=\"img-logo\" src=\"");
      out.print(request.getContextPath());
      out.write("/img/logo.png\" alt=\"\"></a>         \n");
      out.write("    </header>\n");
      out.write("     <!-- content header -->\n");
      out.write("    <div class=\"title-text\">\n");
      out.write("        <div>會員中心</div>\n");
      out.write("    </div> \n");
      out.write("    <!-- side-bar -->\n");
      out.write("    <div class=\"row-offcanvas row-offcanvas-left\">\n");
      out.write("      <div id=\"sidebar\" class=\"sidebar-offcanvas\">\n");
      out.write("          <div class=\"col-md-12\">\n");
      out.write("                <h3 style=\"text-align: center;\">功能列表</h3>\n");
      out.write("            <ul class=\"nav nav-pills nav-stacked\">\n");
      out.write("            \t<li id=\"information\" class=\"click-me active\"><a href=\"#\"><i class=\"fa fa-user\"></i>會員基本資料</a></li>\n");
      out.write("                <li id=\"info-edit\" class=\"click-me\"><a href=\"#\"><i class=\"fas fa-edit\"></i>會員資料修改</a></li>\n");
      out.write("                <li id=\"password-edit\" class=\"click-me\"><a href=\"#\"><i class=\"fa fa-key\"></i>變更密碼</a></li>\n");
      out.write("                <li id=\"check-order\" class=\"click-me\"><a href=\"#\"><i class=\"fa fa-search\"></i>查詢訂單</a></li>\n");
      out.write("                <li id=\"payment\" class=\"click-me\"><a href=\"#\"><i class=\"far fa-credit-card\"></i>付款方式</a></li>\n");
      out.write("                <li id=\"cheap\" class=\"click-me\"><a href=\"#\"><i class=\"fa fa-gift\"></i>套裝優惠</a></li>\n");
      out.write("            </ul>\n");
      out.write("          </div>\n");
      out.write("      </div>\n");
      out.write("      <div id=\"main\">\n");
      out.write("      \t\t<div id=\"info\" class=\"row info-form\">\n");
      out.write("\t          <form method=\"POST\" action=\"\">\n");
      out.write("\t              <fieldset>\n");
      out.write("\t                  <legend><i class=\"fas fa-user-circle\"></i> 會員基本資料</legend>\n");
      out.write("\t                  <div class=\"panel panel-warning\" style=\"width:90%; margin-left:50px;\">\n");
      out.write("\t\t\t            <div class=\"panel-heading\">\n");
      out.write("\t\t\t                <h3 class=\"panel-title\"><i class=\"far fa-campground\"></i> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memVO.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\n");
      out.write("\t\t\t            </div>\n");
      out.write("\t\t\t            <div class=\"panel-body\">\n");
      out.write("\t\t\t                <div class=\"row\">\n");
      out.write("\t\t\t                    <div class=\"col-md-10 pull-right\"> \n");
      out.write("\t\t\t                        <table class=\"table table-user-information\">\n");
      out.write("\t\t\t                        <tbody>\n");
      out.write("\t\t\t                            <tr>\n");
      out.write("\t\t\t\t                            <td>會員編號:</td>\n");
      out.write("\t\t\t\t                            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memVO.mem_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("\t\t\t                            </tr>\n");
      out.write("\t\t\t                            <tr>\n");
      out.write("\t\t\t\t                            <td>會員狀態:</td>\n");
      out.write("\t\t\t\t                            <td>");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t                            </tr>\n");
      out.write("\t\t\t                            <tr>\n");
      out.write("\t\t\t\t                            <td>電子信箱:</td>\n");
      out.write("\t\t\t\t                            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memVO.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("\t\t\t                            </tr>\n");
      out.write("\t\t\t                            <tr>\n");
      out.write("\t\t\t\t                            <td>會員生日:</td>\n");
      out.write("\t\t\t\t                            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memVO.birthday}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("\t\t\t                            </tr>\n");
      out.write("\t\t\t                            <tr>\n");
      out.write("\t\t\t\t                            <td>手機號碼:</td>\n");
      out.write("\t\t\t\t                            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memVO.phone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("\t\t\t                            </tr>\n");
      out.write("\t\t\t                            <tr>\n");
      out.write("\t\t\t\t                            <td>國籍:</td>\n");
      out.write("\t\t\t\t                            <td>");
      //  c:choose
      org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
      boolean _jspx_th_c_005fchoose_005f1_reused = false;
      try {
        _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
        _jspx_th_c_005fchoose_005f1.setParent(null);
        int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
        if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
            //  c:when
            org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
            boolean _jspx_th_c_005fwhen_005f1_reused = false;
            try {
              _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
              _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
              // /front-end/member/Member.jsp(105,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memVO.nation == 'tw'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
              int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
              if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\n");
                  out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<img style=\"width:30px; height:20px;\" src=\"");
                  out.print(request.getContextPath());
                  out.write("/img/taiwan.png\">\n");
                  out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
                  int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
              _jspx_th_c_005fwhen_005f1_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
            }
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
            //  c:when
            org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f2 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
            boolean _jspx_th_c_005fwhen_005f2_reused = false;
            try {
              _jspx_th_c_005fwhen_005f2.setPageContext(_jspx_page_context);
              _jspx_th_c_005fwhen_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
              // /front-end/member/Member.jsp(108,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fwhen_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memVO.nation == 'us'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
              int _jspx_eval_c_005fwhen_005f2 = _jspx_th_c_005fwhen_005f2.doStartTag();
              if (_jspx_eval_c_005fwhen_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\n");
                  out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<img style=\"width:30px; height:20px;\" src=\"");
                  out.print(request.getContextPath());
                  out.write("/img/USA.png\">\n");
                  out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
                  int evalDoAfterBody = _jspx_th_c_005fwhen_005f2.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fwhen_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
              _jspx_th_c_005fwhen_005f2_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f2_reused);
            }
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
            if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
              return;
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
        _jspx_th_c_005fchoose_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
      }
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t                            </tr>\n");
      out.write("\t\t\t                            <tr>\n");
      out.write("\t\t\t\t                            <td>性別:</td>\n");
      out.write("\t\t\t\t                            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memVO.sexual}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("\t\t\t                            </tr>\n");
      out.write("\t\t\t                        </tbody>\n");
      out.write("\t\t\t                        </table> \n");
      out.write("\t\t\t                    </div>\n");
      out.write("\t\t\t                </div>\n");
      out.write("\t\t\t            </div>\n");
      out.write("\t\t\t        </div>      \n");
      out.write("\t              </fieldset>\n");
      out.write("\t          </form>\n");
      out.write("\t      </div>\n");
      out.write("\t      <div id=\"info-show\" class=\"row info-form\" style=\"display:none;\">\n");
      out.write("\t          <form method=\"POST\" action=\"\">\n");
      out.write("\t              <fieldset>\n");
      out.write("\t                  <legend><i class=\"fa fa-edit\"></i> 修改基本資料</legend>\n");
      out.write("\t                  <div class=\"input-group input-group-icon\">\n");
      out.write("\t                          <div class=\"input-name\">姓名：</div>\n");
      out.write("\t                  <input type=\"text\" placeholder=\"姓名 (長度6-12字)\" name=\"name\" minlength=\"6\" maxlength=\"12\"/>\n");
      out.write("\t                  <div class=\"input-icon\"><i class=\"fa fa-user\"></i></div>\n");
      out.write("\t                      <p id=\"errorMsgName\" style=\"font-size:2px; color:red; margin-left:105px;\"></p>\n");
      out.write("\t                  </div>\n");
      out.write("\t                  <div class=\"input-group input-group-icon\">\n");
      out.write("\t                          <div class=\"input-name\">帳號：</div>\n");
      out.write("\t                  <input type=\"text\" placeholder=\"帳號 (長度8-12字 )\" name=\"user_id\" minlength=\"8\" maxlength=\"12\"/>\n");
      out.write("\t                  <div class=\"input-icon\"><i class=\"far fa-user-circle\"></i></div>\n");
      out.write("\t                      <p id=\"errorMsgUserId\" style=\"font-size:2px; color:red; margin-left:105px;\"></p>\n");
      out.write("\t                  </div>\n");
      out.write("\t                  <div class=\"input-group input-group-icon\">\n");
      out.write("\t                          <div class=\"input-name\">電子信箱：</div>\n");
      out.write("\t                  <input id=\"check-repeat-email\" type=\"email\" placeholder=\"電子信箱\" name=\"email\"/>\n");
      out.write("\t                  <div class=\"input-icon\"><i class=\"fa fa-envelope\"></i></div>\n");
      out.write("\t                      <p id=\"errorMsgEmail\" style=\"font-size:2px; color:red; margin-left:105px;\"></p>\n");
      out.write("\t                  </div>\n");
      out.write("\t                  <div class=\"input-group input-group-icon\">\n");
      out.write("\t                          <div class=\"input-name\">手機號碼：</div>\n");
      out.write("\t                  <input type=\"text\" placeholder=\"手機號碼\" name=\"phone\"/>\n");
      out.write("\t                  <div class=\"input-icon\"><i class=\"far fa-phone-alt\"></i></div>\n");
      out.write("\t                  </div>\n");
      out.write("\t                  <div class=\"input-group input-group-icon\">\n");
      out.write("\t                          <div class=\"input-name\">出生年月日：</div>\n");
      out.write("\t                  <input id=\"birthday\" type=\"text\" placeholder=\"生日\" name=\"birthday\"/>\n");
      out.write("\t                  <div class=\"input-icon\"><i class=\"far fa-birthday-cake\"></i></div>\n");
      out.write("\t                  </div>\n");
      out.write("\t                  <div class=\"input-group input-group-icon\">\n");
      out.write("\t                          <div class=\"input-name\">身分證字號：</div>\n");
      out.write("\t                  <input type=\"text\" placeholder=\"身分證字號\" name=\"personal_id\"/>\n");
      out.write("\t                  <div class=\"input-icon\"><i class=\"far fa-user-circle\"></i></div>\n");
      out.write("\t                  <p id=\"errorMsgID\" style=\"font-size:2px; color:red; margin-left:105px;\"></p>\n");
      out.write("\t                  </div>\n");
      out.write("\t                  <div class=\"input-group input-group-icon\">\n");
      out.write("\t                          <div class=\"input-name\">國籍：</div>\n");
      out.write("\t                  <input type=\"text\" id=\"country\" placeholder=\"國籍\">\n");
      out.write("\t                  <input type=\"hidden\" name=\"nation\" id=\"country_code\" />\n");
      out.write("\t                  <div class=\"input-icon\"><i class=\"fas fa-globe-asia\"></i></div>\n");
      out.write("\t                  </div>\n");
      out.write("\t                  <div class=\"col-half\">\n");
      out.write("\t                      <div class=\"input-name\">性別：</div>\n");
      out.write("\t                      <div class=\"input-group\">           \n");
      out.write("\t                      <input type=\"radio\" name=\"gender\" value=\"male\" id=\"gender-male\"/>\n");
      out.write("\t                      <label for=\"gender-male\">男</label>\n");
      out.write("\t                      <input type=\"radio\" name=\"gender\" value=\"female\" id=\"gender-female\"/>\n");
      out.write("\t                      <label for=\"gender-female\">女</label>\n");
      out.write("\t                      </div>\n");
      out.write("\t                  </div>\n");
      out.write("\t                  <br>\n");
      out.write("\t              </fieldset>\n");
      out.write("\t              <button type=\"submit\" class=\"form-submit\">送出申請</button>\n");
      out.write("\t          </form>\n");
      out.write("\t      </div>\n");
      out.write("          <div id=\"password-show\" class=\"row info-form\" style=\"display: none;\">\n");
      out.write("              <form method=\"POST\" action=\"\">\n");
      out.write("                  <fieldset>\n");
      out.write("                      <legend><i class=\"fa fa-key\"></i> 變更密碼</legend>\n");
      out.write("                      <div class=\"input-group input-group-icon\">\n");
      out.write("                          <div class=\"input-name\">舊密碼：</div>\n");
      out.write("                              <input type=\"password\" placeholder=\"舊密碼 (長度8-12字且不包含特殊符號)\" name=\"user_pwd\" minlength=\"8\" maxlength=\"12\"/>\n");
      out.write("                          <div class=\"input-icon\"><i class=\"fa fa-key\"></i></div>\n");
      out.write("                          <p id=\"errorMsgUserPwd\" style=\"font-size:2px; color:red; margin-left:105px;\"></p>\n");
      out.write("                      </div>\n");
      out.write("                      <div class=\"input-group input-group-icon\">\n");
      out.write("                          <div class=\"input-name\">新密碼：</div>\n");
      out.write("                              <input type=\"password\" placeholder=\"新密碼 (長度8-12字且不包含特殊符號)\" name=\"user_pwd\" minlength=\"8\" maxlength=\"12\"/>\n");
      out.write("                          <div class=\"input-icon\"><i class=\"fa fa-key\"></i></div>\n");
      out.write("                          <p id=\"errorMsgUserPwd\" style=\"font-size:2px; color:red; margin-left:105px;\"></p>\n");
      out.write("                      </div>\n");
      out.write("                      <div class=\"input-group input-group-icon\">\n");
      out.write("                          <div class=\"input-name\">新密碼確認：</div>\n");
      out.write("                              <input id=\"check-repeat-pwd\" type=\"password\" placeholder=\"再次輸入新密碼\" name=\"re_enter_pwd\"/>\n");
      out.write("                          <div class=\"input-icon\"><i class=\"fa fa-key\"></i></div>\n");
      out.write("                          <p id=\"errorMsgUserRePwd\" style=\"font-size:2px; color:red; margin-left:105px;\"></p>\n");
      out.write("                      </div>\n");
      out.write("                      <br>\n");
      out.write("                  </fieldset>\n");
      out.write("                  <button type=\"submit\" class=\"form-submit\">送出申請</button>\n");
      out.write("              </form>\n");
      out.write("          </div>\n");
      out.write("          <div id=\"credit-show\" class=\"row info-form\" style=\"display: none;\">\n");
      out.write("              <form>\n");
      out.write("                  <fieldset>\n");
      out.write("                      <legend><i class=\"far fa-credit-card\"></i> 變更付款方式</legend>\n");
      out.write("                      <div class=\"creditcard\" style=\"display: none;\">\n");
      out.write("                          <h4 class=\"cardnumber\">5148 6934 2929 2746</h4>\n");
      out.write("                          <h6>CARDHOLDER NAME</h6>\n");
      out.write("                          <p class=\"cardholder\">JOHN DOE</p>\n");
      out.write("                          <p class=\"exp\">04/22</p>\n");
      out.write("                          <i class=\"fas fa-minus-circle delete-creditcard\"></i>\n");
      out.write("                          <div class=\"creditcard-logo\">\n");
      out.write("                              <img style=\"width: 70px; height: 70px;\" src=\"");
      out.print(request.getContextPath());
      out.write("/img/Affinity-Partnership_VISA_600x600 LOGO-01.png\" alt=\"\" />\n");
      out.write("                          </div>\n");
      out.write("                      </div>\n");
      out.write("                      <div class=\"creditcardplus\">\n");
      out.write("                          <i class=\"plus-card fas fa-plus fa-3x\"></i>         \n");
      out.write("                      </div>\n");
      out.write("                      <br>\n");
      out.write("                  </fieldset>\n");
      out.write("              </form>\n");
      out.write("              <div class=\"credit-lightBox\" style=\"display: none;\">\n");
      out.write("                  <form id=\"credit\" action=\"#\">\n");
      out.write("                      <div class=\"container-fluid grid\">              \n");
      out.write("                        <div class=\"row pull-center\">\n");
      out.write("                          <div class=\"position-card col-md-4\">            \n");
      out.write("                            <div class=\"well\">         \n");
      out.write("                              <div class=\"row card\">\n");
      out.write("                              </div>\n");
      out.write("                              <br/>           \n");
      out.write("                              <div class=\"row-fluid\">\n");
      out.write("                                <div class=\"col-md-8\">\n");
      out.write("                                  <div class=\"form-group\">\n");
      out.write("                                    <label>卡號 </label>\n");
      out.write("                                    <input type=\"text\" name=\"payment\" class=\"form-control\" />\n");
      out.write("                                  </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"col-md-4\">\n");
      out.write("                                  <div class=\"form-group\">\n");
      out.write("                                    <label>到期日</label>            \n");
      out.write("                                    <input type=\"text\" placeholder=\"MM/YY\" name=\"expiry\" class=\"form-control\" />              \n");
      out.write("                                  </div>\n");
      out.write("                                </div>\n");
      out.write("                              </div>         \n");
      out.write("                              <div class=\"row-fluid\">\n");
      out.write("                                <div class=\"col-md-8\">\n");
      out.write("                                  <div class=\"form-group\">\n");
      out.write("                                    <label>持卡人</label>\n");
      out.write("                                    <input type=\"text\" name=\"name\" class=\"form-control\" />\n");
      out.write("                                  </div>\n");
      out.write("                                </div>           \n");
      out.write("                                <div class=\"col-md-4\">\n");
      out.write("                                  <div class=\"form-group\">\n");
      out.write("                                    <label>安全碼 </label>\n");
      out.write("                                    <input type=\"text\" name=\"cvv\" class=\"form-control\" />\n");
      out.write("                                  </div>\n");
      out.write("                                </div>\n");
      out.write("                              </div>\n");
      out.write("                              <div class=\"row \">\n");
      out.write("                                <div class=\"col-md-12 text-right\">\n");
      out.write("                                  <button type=\"submit\" class=\"btn btn-success\">提交</button>\n");
      out.write("                                  <button id=\"cancel-plus\" type=\"button\" class=\"btn btn-info\">取消</button>\n");
      out.write("                                </div>     \n");
      out.write("                              </div>\n");
      out.write("                            </div>\n");
      out.write("                          </div>\n");
      out.write("                      </div>             \n");
      out.write("                  </form>\n");
      out.write("              </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    <!-- footer -->\n");
      out.write("    <footer class=\"site-footer\">\n");
      out.write("        <div class=\"footer-container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("            <div class=\"col-sm-12 col-md-6\">\n");
      out.write("                <h6>關於我們</h6>\n");
      out.write("                <p class=\"text-justify\"><i>Maison Camp</i> 豪華露營提供多項的活動的安排與遊憩設施。<br>適合親子或三五好友一同前來放鬆體驗。<br>豪華露營、 野奢莊園 、野奢酒店的概念，要帶給您一種全新的露營體驗。<br>快來與我們一起聽流水蟲鳴鳥叫 與森林一同呼吸。</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-xs-6 col-md-2\">\n");
      out.write("                <h6>快速連結</h6>\n");
      out.write("                <ul class=\"footer-links\">\n");
      out.write("                <li><a href=\"\">會員登入</a></li>\n");
      out.write("                <li><a href=\"\">立即訂房</a></li>\n");
      out.write("                <li><a href=\"\">精選商城</a></li>\n");
      out.write("                <li><a href=\"\">預約活動</a></li>\n");
      out.write("                <li><a href=\"\">聯繫我們</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-xs-6 col-md-3\">\n");
      out.write("                <a href=\"\"><img class=\"footer-map\" src=\"");
      out.print(request.getContextPath());
      out.write("/img/footer.png\" style=\"height: 160px; width: 300px;\" alt=\"\"></a>\n");
      out.write("            </div>\n");
      out.write("            </div>\n");
      out.write("            <hr>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"footer-container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("            <div class=\"col-md-8 col-sm-6 col-xs-12\">\n");
      out.write("                <p class=\"copyright-text\">Copyright &copy; 2021 All Rights Reserved by \n");
      out.write("            <a href=\"#\">Maison Camp</a>.\n");
      out.write("                </p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-4 col-sm-6 col-xs-12\">\n");
      out.write("                <ul class=\"social-icons\">\n");
      out.write("                <li><a class=\"facebook\" href=\"#\"><i class=\"fab fa-facebook-f\"></i></a></li>\n");
      out.write("                <li><a class=\"twitter\" href=\"#\"><i class=\"fab fa-twitter\"></i></a></li>\n");
      out.write("                <li><a class=\"dribbble\" href=\"#\"><i class=\"fab fa-dribbble\"></i></a></li>\n");
      out.write("                <li><a class=\"linkedin\" href=\"#\"><i class=\"fab fa-linkedin\"></i></a></li>   \n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </footer>\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.min.js\"></script>\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/card/2.5.0/jquery.card.js\"></script>\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\" integrity=\"sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/front-end/member.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /front-end/member/Member.jsp(81,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memVO.status == '0'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t未驗證\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t已驗證\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f1_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t已驗證\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
      _jspx_th_c_005fotherwise_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f1_reused);
    }
    return false;
  }
}
