/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2020-12-23 07:11:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.front_002dend;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.member.model.*;

public final class front_002dindex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1608636200000L));
    _jspx_dependants.put("jar:file:/Users/tomgu/CEA101_WebApp/CEA101G3/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/CEA101G3/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1064305020000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.member.model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	MemberVO memVO = (MemberVO) session.getAttribute("memVO");	
	List<String> errorMsgs = (List<String>) request.getAttribute("errorMsgs");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900\" rel=\"stylesheet\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://pro.fontawesome.com/releases/v5.10.0/css/all.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/front-end/style.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/front-end/login.css\">\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/png\" href=\"");
      out.print(request.getContextPath());
      out.write("/img/homelogo.png\">\n");
      out.write("<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css\">\n");
      out.write("<title>Maison Camp | 露營家</title>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write(" <div id=\"parallax-world-of-ugg\">\n");
      out.write("        <div class=\"block\">\n");
      out.write("        <header class=\"header\">\n");
      out.write("            <nav role=\"navigation\">\n");
      out.write("                <div id=\"menuToggle\">\n");
      out.write("                    <input type=\"checkbox\" id=\"checkboxtoggle\"/>\n");
      out.write("                    <span></span>\n");
      out.write("                    <span></span>\n");
      out.write("                    <span></span>\n");
      out.write("                    <ul id=\"menu\">\n");
      out.write("                        <a href=\"");
      out.print(request.getContextPath());
      out.write("/front-end/front-index.jsp\"><li>首頁</li></a>\n");
      out.write("                        <a href=\"");
      out.print(request.getContextPath());
      out.write("/front-end/news/News.jsp\"><li>最新消息</li></a>\n");
      out.write("                        <a href=\"#\"><li>會員登入</li></a>\n");
      out.write("                        <a href=\"");
      out.print(request.getContextPath());
      out.write("/front-end/room-type/RoomType.jsp\"><li>帳型介紹</li></a>\n");
      out.write("                        <a href=\"");
      out.print(request.getContextPath());
      out.write("/front-end/room-booking/RoomBooking.jsp\"><li>立即訂房</li></a>\n");
      out.write("                        <a href=\"#\"><li>精選商城</li></a>\n");
      out.write("                        <a href=\"#\"><li>活動預約</li></a>\n");
      out.write("                        <a href=\"#\"><li>聯絡我們</li></a>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </nav>\n");
      out.write("            <div class=\"col-xs-4 col-12 logo\">\n");
      out.write("                <a href=\"#\"><img id=\"logoo\" class=\"img-logo\" src=\"");
      out.print(request.getContextPath());
      out.write("/img/logo.png\" alt=\"\"></a>\n");
      out.write("            </div> \n");
      out.write("            ");
      //  c:choose
      org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
      boolean _jspx_th_c_005fchoose_005f0_reused = false;
      try {
        _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fchoose_005f0.setParent(null);
        int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
        if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("            \t");
            //  c:when
            org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
            boolean _jspx_th_c_005fwhen_005f0_reused = false;
            try {
              _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
              _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
              // /front-end/front-index.jsp(50,13) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memVO == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
              int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
              if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\n");
                  out.write("\t            \t<ul class=\"signin-links\">\n");
                  out.write("\t        \t\t\t<li><a class=\"\" href=\"");
                  out.print(request.getContextPath());
                  out.write("/front-end/signup/SignUp.jsp\"><i class=\"material-icons signup-icon\">account_circle</i>註冊</a></li>\n");
                  out.write("\t        \t\t\t<li><a class=\"signin\" href=\"#\"><i class=\"material-icons login-icon\">face</i>登入</a></li>\n");
                  out.write("\t      \t\t\t</ul>\t\n");
                  out.write("            \t");
                  int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
              _jspx_th_c_005fwhen_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
            }
            out.write("\n");
            out.write("            \t");
            //  c:otherwise
            org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
            boolean _jspx_th_c_005fotherwise_005f0_reused = false;
            try {
              _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
              _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
              int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
              if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\n");
                  out.write("            \t\t<ul class=\"signin-links\">\n");
                  out.write("\t        \t\t\t<li><i style=\"margin-right:7px; color:#c15c16;\" class=\"fas fa-child fa-1x\"></i>");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memVO.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write(" 歡迎回來<i style=\"color:#496b6b; margin: 0 10px 0 5px;\" class=\"fas fa-exclamation\"></i><a class=\"signin\" href=\"");
                  out.print(request.getContextPath());
                  out.write("/Member.do?action=logout\"><i class=\"fas fa-sign-out-alt\"></i></a></li>\n");
                  out.write("\t      \t\t\t</ul>\n");
                  out.write("            \t");
                  int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
              _jspx_th_c_005fotherwise_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
            }
            out.write("\n");
            out.write("            ");
            int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
        _jspx_th_c_005fchoose_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
      }
      out.write("\n");
      out.write("        </header>\n");
      out.write("        <div id=\"lightBox\" style=\"display: none;\">\n");
      out.write("          <div id=\"cancelLogin\">\n");
      out.write("            <i class=\"fas fa-times fa-2x\"></i>\n");
      out.write("          </div> \n");
      out.write("           <div class=\"loginpanel\">\n");
      out.write("            <div class=\"content-1\" style=\"display: block;\">\n");
      out.write("                <div>\n");
      out.write("                    <h2 class=\"title\">會員登入</h2>\n");
      out.write("                </div>\n");
      out.write("                <form method=\"post\" action=\"");
      out.print(request.getContextPath());
      out.write("/MemberLoginHandler\">\n");
      out.write("                <div class=\"txt\">\n");
      out.write("                  <input id=\"user\" type=\"text\" placeholder=\"請輸入Email\" name=\"mem_email\"/>\n");
      out.write("                  <label for=\"user\" class=\"entypo-user\"></label>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"txt\">\n");
      out.write("                  <input id=\"pwd\" type=\"password\" placeholder=\"請輸入密碼\" name=\"mem_user_pwd\"/>\n");
      out.write("                  <label for=\"pwd\" class=\"entypo-lock\"></label>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"buttons\">\n");
      out.write("                  <input type=\"submit\" value=\"登入\"/>\n");
      out.write("                  <span>\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/front-end/signup/SignUp.jsp\" class=\"entypo-user-add register\">加入會員</a>\n");
      out.write("                  </span>\n");
      out.write("                </div>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("           <div class=\"content-3\" style=\"display: none;\">\n");
      out.write("                <div>\n");
      out.write("                    <h2 class=\"title\">忘記密碼</h2>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"txt\">\n");
      out.write("                  <input id=\"user\" type=\"email\" placeholder=\"Email\" />\n");
      out.write("                  <label for=\"user\" class=\"entypo-mail\"></label>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"txt\">\n");
      out.write("                  <input id=\"pwd\" type=\"date\" />\n");
      out.write("                  <label for=\"pwd\" class=\"entypo-calendar\"></label>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"buttons\">\n");
      out.write("                  <input type=\"submit\" value=\"重寄密碼\"/>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("             <div class=\"hr\">\n");
      out.write("              <div></div>\n");
      out.write("              <div></div>\n");
      out.write("              <div></div>\n");
      out.write("            </div>      \n");
      out.write("            <div class=\"social\">\n");
      out.write("                <div class=\"align\">\n");
      out.write("                    <li class=\"login\"></li>\n");
      out.write("                    <p>會員登入</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"align\">\n");
      out.write("                    <li class=\"forget\"></li>\n");
      out.write("                    <p>忘記密碼</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div> \n");
      out.write("         <section>\n");
      out.write("            <div id=\"carouselExampleControls\" class=\"carousel slide lickme\" data-ride=\"carousel\">\n");
      out.write("                <div class=\"carousel-inner\">\n");
      out.write("                  <div class=\"carousel-item active\">\n");
      out.write("                    <a href=\"\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/img/slide2.png\" class=\"d-block w-100\" alt=\"...\"></a>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"carousel-item\">\n");
      out.write("                    <a href=\"\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/img/slide1.jpg\" class=\"d-block w-100\" alt=\"...\"></a>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"carousel-item\">\n");
      out.write("                    <a href=\"\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/img/slide3.jpg\" class=\"d-block w-100\" alt=\"...\"></a>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("                <a class=\"carousel-control-prev\" href=\"#carouselExampleControls\" role=\"button\" data-slide=\"prev\">\n");
      out.write("                  <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\n");
      out.write("                  <span class=\"sr-only\">Previous</span>\n");
      out.write("                </a>\n");
      out.write("                <a class=\"carousel-control-next\" href=\"#carouselExampleControls\" role=\"button\" data-slide=\"next\">\n");
      out.write("                  <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\n");
      out.write("                  <span class=\"sr-only\">Next</span>\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"marquee\">\n");
      out.write("              <p class=\"news-title\">NEWS</p>\n");
      out.write("              <ul>\n");
      out.write("                <a href=\"\"><li>【2020-12-31】Maison Camp 集聚一堂草地音樂會！</li></a>\n");
      out.write("                <a href=\"\"><li>【2021-01-20】Maison Camp 最新訂房優惠開跑囉！</li></a>\n");
      out.write("                <a href=\"\"><li>【2021-03-31】Maison Camp 商城農產品大特價！</li></a>\n");
      out.write("              </ul>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("         <section>\n");
      out.write("          <div id=\"book-checking\">\n");
      out.write("            <div class=\"book-title\">豪華露營預約狀況即時查詢</div>\n");
      out.write("            <div class=\"checking-date\">\n");
      out.write("              <div class=\"mobile-checking\">\n");
      out.write("                <a href=\"#\">\n");
      out.write("                  <img src=\"");
      out.print(request.getContextPath());
      out.write("/img/bed-4.svg\" alt=\"\">\n");
      out.write("                  <span>四人帳</span>\n");
      out.write("                </a>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"mobile-checking\">\n");
      out.write("                <a href=\"#\">\n");
      out.write("                  <img src=\"");
      out.print(request.getContextPath());
      out.write("/img/bed-2.svg\" alt=\"\">\n");
      out.write("                  <span>二人帳</span>\n");
      out.write("                </a>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"mobile-checking\">\n");
      out.write("                <a href=\"#\">\n");
      out.write("                  <img src=\"");
      out.print(request.getContextPath());
      out.write("/img/bed-1.svg\" alt=\"\">\n");
      out.write("                  <span>單人帳</span>\n");
      out.write("                </a>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </section> \n");
      out.write("        <section>\n");
      out.write("          <div class=\"rest-title\">\n");
      out.write("            <div class=\"rest-title-container\">\n");
      out.write("              <h1>林間休憩</h1>\n");
      out.write("              數種住宿選擇，讓您和家人朋友一起迎接自然<br>\n");
      out.write("              我們提供現在最流行的 Glamping 住宿， Glamping是一種豪華露營、 野奢莊園 、野奢酒店的概念，要帶給您一種全新的露營體驗\n");
      out.write("            </div>\n");
      out.write("            <div class=\"rest\">\n");
      out.write("              <figure class=\"rest-box\">\n");
      out.write("                <img class=\"img-responsive\" src=\"");
      out.print(request.getContextPath());
      out.write("/img/house1.png\" alt=\"\">\n");
      out.write("                <figcaption class=\"rest-box-text\">豐庭度假屋</figcaption>\n");
      out.write("              </figure>\n");
      out.write("              <figure class=\"rest-box\">\n");
      out.write("                <img class=\"img-responsive\" src=\"");
      out.print(request.getContextPath());
      out.write("/img/house2.png\" alt=\"\">\n");
      out.write("                <figcaption class=\"rest-box-text\"><i>Maison Camp</i>豪華露營</figcaption>\n");
      out.write("              </figure>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </section>\n");
      out.write("      </div>\n");
      out.write("         <section>\n");
      out.write("            <div class=\"parallax-two\">\n");
      out.write("              <div class=\"presentation-nav\">\n");
      out.write("                <ul>\n");
      out.write("                  <li class=\"presentation-nav-normal\">\n");
      out.write("                    <span>精選商城</span>\n");
      out.write("                    <i class=\"fa fa-shopping-cart\"></i>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"presentation-nav-normal\">\n");
      out.write("                    <span>活動預定</span>\n");
      out.write("                    <i class=\"fa fa-gavel\"></i>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"presentation-nav-normal\">\n");
      out.write("                    <span>人文休憩</span>\n");
      out.write("                    <i class=\"fa fa-heart\"></i>\n");
      out.write("                  </li>        \n");
      out.write("                </ul>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"presentation-text\">\n");
      out.write("                <div class=\"presentation-bg\">\n");
      out.write("                  <h1>精選商城</h1>\n");
      out.write("                  <h4>多種自有農場水果加工品</h4>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </section>\n");
      out.write("            <section>\n");
      out.write("            <div class=\"block\">\n");
      out.write("                <img style=\"width: 100%; position: relative;\" src=\"");
      out.print(request.getContextPath());
      out.write("/img/brooke-cagle-xJ0Isuqt9ys-unsplash.jpg\" alt=\"\">\n");
      out.write("                <div class=\"presentation-text2\">\n");
      out.write("                  <div class=\"presentation-bg2\">\n");
      out.write("                    <h1>活動預定</h1>\n");
      out.write("                    <h4>多種精彩採果趣</h4>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("            </div>         \n");
      out.write("          </section>\n");
      out.write("          <section>\n");
      out.write("            <div class=\"parallax-three\">\n");
      out.write("              <div class=\"presentation-text\">\n");
      out.write("                <div class=\"presentation-bg\">\n");
      out.write("                  <h1>休憩體驗</h1>\n");
      out.write("                  <h4>與家人朋友一同享受美好環境</h4>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </section>\n");
      out.write("       <div class=\"block\"> \n");
      out.write("           <footer class=\"site-footer\">\n");
      out.write("          <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <div class=\"col-sm-12 col-md-6\">\n");
      out.write("                <h6>關於我們</h6>\n");
      out.write("                <p class=\"text-justify\"><i>Maison Camp</i> 豪華露營提供多項的活動的安排與遊憩設施。<br>適合親子或三五好友一同前來放鬆體驗。<br>豪華露營、 野奢莊園 、野奢酒店的概念，要帶給您一種全新的露營體驗。<br>快來與我們一起聽流水蟲鳴鳥叫 與森林一同呼吸。</p>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-xs-6 col-md-2\">\n");
      out.write("                <h6>快速連結</h6>\n");
      out.write("                <ul class=\"footer-links\">\n");
      out.write("                  <li><a href=\"\">會員登入</a></li>\n");
      out.write("                  <li><a href=\"\">立即訂房</a></li>\n");
      out.write("                  <li><a href=\"\">精選商城</a></li>\n");
      out.write("                  <li><a href=\"\">預約活動</a></li>\n");
      out.write("                  <li><a href=\"\">聯繫我們</a></li>\n");
      out.write("                </ul>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-xs-6 col-md-3\">\n");
      out.write("                <a href=\"\"><img class=\"footer-map\" src=\"");
      out.print(request.getContextPath());
      out.write("/img/footer.png\" style=\"height: 160px; width: 300px;\" alt=\"\"></a>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <hr>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <div class=\"col-md-8 col-sm-6 col-xs-12\">\n");
      out.write("                <p class=\"copyright-text\">Copyright &copy; 2021 All Rights Reserved by \n");
      out.write("             <a href=\"#\">Maison Camp</a>.\n");
      out.write("                </p>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-md-4 col-sm-6 col-xs-12\">\n");
      out.write("                <ul class=\"social-icons\">\n");
      out.write("                  <li><a class=\"facebook\" href=\"#\"><i class=\"fa fa-facebook\"></i></a></li>\n");
      out.write("                  <li><a class=\"twitter\" href=\"#\"><i class=\"fa fa-twitter\"></i></a></li>\n");
      out.write("                  <li><a class=\"dribbble\" href=\"#\"><i class=\"fa fa-dribbble\"></i></a></li>\n");
      out.write("                  <li><a class=\"linkedin\" href=\"#\"><i class=\"fa fa-linkedin\"></i></a></li>   \n");
      out.write("                </ul>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("    </footer>\n");
      out.write("    </div>\n");
      out.write("   </div>\n");
      out.write("        <script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/bootstrap/bootstrap.min.js\"></script>\n");
      out.write("        <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/front-end/index.js\"></script>\n");
      out.write("        <script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /front-end/front-index.jsp(293,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty errorMsgs}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t<script type=\"text/javascript\">\n");
          out.write("\t\t\t\tswal(\"帳密錯誤\",\"請重新輸入\",\"error\");\n");
          out.write("\t\t\t\t$(\"#lightBox\").css(\"display\",\"\");\n");
          out.write("\t\t\t</script>\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
